apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: cloudflare
stringData:
    token: ENC[AES256_GCM,data:xgxExHYQ2Jppl+GTQK8cvbL58oKLydrteYtzzJuNhKEOUifPGlv17DhYGXyhKWk1Xi7vqZYrDHdQW73mtddwN6XDnIOKlbgLA9OPZaNfFTKE+nbbSshaJtP7uNgz4hsv5KWaY0CF2OAAhPfF9Px+pXU9XbqHYSHxlTHaOj29GA2Uv/AyJMfiSvRI9mCm2w1qdqSH72CQukGVGpakTh6FmkhhLjFOHXbiN/7Xg50g7jXYJ+RUAlcjvZzcCigUw0Af32Wa87sFbEf6z/UDwe2v0rltnWedzhb73PhcLUN1yapp3M/iEk+Q7n8ddQN68zMl,iv:wbT6luilOdHloPznIOCJEhOvArwHQN6rkzvIT5hhdh0=,tag:u5+fA4Dwh/1SMu2eg+E9Wg==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eEowQ0tMb1hGWnVsMnVm
            U2NzUGltVXQ4Sjd6SkVyY2xPWjRjejB2N0g4CjYyRmdwek02dVNNa1dGVXhDT0d0
            aTBCb2QwSVZEY0lZY2NUU2JVbTlTRm8KLS0tIGdNbklkTmh6MDJsQUJ5R0FOVng1
            STJ6Z1VwTjdtUUJPZXo2b01Dc0gyQXcK6z6dxWEISFXgAwXd+oVZ7RSAx+Ix0FZy
            KF8kYxRZ/GV0AhMWFT3iEp2L/D/Xw8TlYZS8MCcW8Ohiy/oJWk1DfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T00:08:17Z"
    mac: ENC[AES256_GCM,data:tDwDFPyrHBV09UCNo+i3pI8G1Ch33QfV3dHLSuNIU88j7z50FoUDejOjLqsXeRgyKGkaPexVNaHIwVb1z+iB4klKiBf8zqwWJVV5Lsn6RV1A7B4AGikssrbuVng2pCjZdMKy6oldi+uR3aPi6J9e69jL0w0hrS1maZeKPs0abQk=,iv:ft8iwWixrSaAmUxENJ/oAj7yw4zHoPnAaP3T9HdTrHU=,tag:nV9ohb4ivfdyAcvlF/pgEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
