apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    kubernetes.io/service-name: local-node-exporters
    lolwtf.ca/service: node-exporter
addressType: IPv4
ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
endpoints:
  - addresses: ["10.2.0.20"]
    nodeName: cloudpi4
  - addresses: ["10.2.0.23"]
    nodeName: homepi4-wifi
  - addresses: ["10.2.0.24"]
    nodeName: radiopi0
  - addresses: ["10.2.0.25"]
    nodeName: blinkypi0
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: windows-exporters
  namespace: monitoring
  labels:
    kubernetes.io/service-name: windows-exporters
    lolwtf.ca/service: windows-exporter
addressType: IPv4
ports:
  - name: http-metrics
    port: 9182
    protocol: TCP
endpoints:
  - addresses: ["10.13.37.2"]
    nodeName: tallboy
--- # trivy:ignore:avd-ksv-0108
apiVersion: v1
kind: Service
metadata:
  name: windows-exporters
  namespace: monitoring
  labels:
    lolwtf.ca/service: windows-exporter
    jobLabel: windows-exporter
spec:
  type: ExternalName
  externalName: windows-exporters
  ports:
    - name: http-metrics
      port: 9182
      protocol: TCP
      targetPort: 9182
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: windows-exporters
  namespace: monitoring
  labels:
    lolwtf.ca/service: windows-exporter
    release: prom-stack
spec:
  jobLabel: jobLabel
  endpoints:
    - port: http-metrics
      interval: 30s
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_endpoint_node_name]
          targetLabel: instance
  selector:
    matchLabels:
      lolwtf.ca/service: windows-exporter
  namespaceSelector:
    matchNames:
      - monitoring
--- # trivy:ignore:avd-ksv-0108
apiVersion: v1
kind: Service
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    lolwtf.ca/service: node-exporter
    jobLabel: node-exporter
spec:
  type: ExternalName
  externalName: local-node-exporters
  ports:
    - name: http-metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    lolwtf.ca/service: node-exporter
    release: prom-stack
spec:
  jobLabel: jobLabel
  endpoints:
    - port: http-metrics
      interval: 30s
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_endpoint_node_name]
          targetLabel: instance
  selector:
    matchLabels:
      lolwtf.ca/service: node-exporter
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: local-node-exporters
  namespace: monitoring
  labels:
    lolwtf.ca/service: node-exporter
    release: prom-stack
spec:
  groups:
    - name: local-node-exporters
      rules:
        - alert: PrometheusTargetMissing
          expr: up {endpoint="http-metrics",  namespace="monitoring", service="local-node-exporters"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            message: Prometheus target missing (instance {{ $labels.instance }})
            description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
