apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: screenpi4
  namespace: monitoring
  labels:
    kubernetes.io/service-name: screenpi4
    lolwtf.ca/service: dht22
addressType: IPv4
ports:
  - name: http-metrics
    port: 8000
    protocol: TCP
endpoints:
  - addresses: ["10.2.0.28"]
    nodeName: screenpi4
--- # trivy:ignore:avd-ksv-0108
apiVersion: v1
kind: Service
metadata:
  name: screenpi4
  namespace: monitoring
  labels:
    lolwtf.ca/service: dht22
spec:
  ports:
    - name: http-metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dht22
  namespace: monitoring
  labels:
    lolwtf.ca/service: dht22
    release: prom-stack
spec:
  jobLabel: lolwtf.ca/service
  endpoints:
    - port: http-metrics
      interval: 30s
      honorLabels: true
      path: /
  selector:
    matchLabels:
      lolwtf.ca/service: dht22
  namespaceSelector:
    matchNames:
      - monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: screenpi4
  namespace: monitoring
  labels:
    lolwtf.ca/service: dht22
    release: prom-stack
spec:
  groups:
    - name: screenpi4
      rules:
        - alert: PrometheusTargetMissing
          expr: up {endpoint="http-metrics",  namespace="monitoring", service="screenpi4"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            message: Prometheus target missing (instance {{ $labels.instance }})
            description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
