apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: cluster-gateway
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
spec:
  gatewayClassName: cilium
  listeners:
    - name: http-gateway
      protocol: HTTP
      port: 80
      allowedRoutes:
        kinds:
          - kind: HTTPRoute
    - name: bittorrent-tls
      protocol: HTTPS
      port: 443
      hostname: &hostname "bittorrent.${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: *hostname
    - name: sonarr-tls
      protocol: HTTPS
      port: 443
      hostname: &hostname "sonarr.${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: *hostname
    - name: radarr-tls
      protocol: HTTPS
      port: 443
      hostname: &hostname "radarr.${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: *hostname
    - name: prowlarr-tls
      protocol: HTTPS
      port: 443
      hostname: &hostname "prowlarr.${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: *hostname
    - name: bazarr-tls
      protocol: HTTPS
      port: 443
      hostname: &hostname "bazarr.${SECRET_DOMAIN}"
      tls:
        certificateRefs:
          - kind: Secret
            name: *hostname
