apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${GATEWAY_DOMAIN}
  namespace: default
spec:
  secretName: ${GATEWAY_DOMAIN}
  dnsNames:
    - ${GATEWAY_DOMAIN}
    - unifi.${GATEWAY_DOMAIN}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
