---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./config/crd/standard
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-experimental-apis
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./config/crd/experimental
  prune: true
  sourceRef:
    kind: GitRepository
    name: gateway-api
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api-cluster-gateway
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/clusters/offsite/networking/gateway-api
  prune: true
  dependsOn:
    - name: gateway-api
    - name: gateway-api-experimental-apis
  sourceRef:
    kind: GitRepository
    name: infra
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
