tunnel: b7442b4d-6a9f-45f4-9254-0e97db1eacdd
token-file: /etc/cloudflared/token
metrics: 0.0.0.0:2000
no-autoupdate: true
# ingress:
#   - hostname: cf.folly.lolwtf.ca
#     service: http_status:401
#   - service: http_status:404
# # - hostname: wishin.lolwtf.ca
# #   service: http://wishin.wishin:8080
