apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Mb6hyj4BOJ2J,iv:w0HEU3pSJ6oMFyOO0d2Y8/Buc25ofjeGeDrKMiwvmFc=,tag:x96gyH9/hwSsQRT7m/9TUg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Swq6b6YIDECYCGK0E4IwWiFvjug=,iv:mdsnsNr+vzJbuHrJ0TxIM//ec3LtlQvgVmHFJ1ZqaXk=,tag:9QonNiy/C5vuocSRLHqRQg==,type:str]
    SECRET_FLAMEBOSS_USERNAME: ENC[AES256_GCM,data:C4SYpdrbioc=,iv:V+y5kx/VFYTR69fbNemxHUKxnGjDgiTndJ0iR81DHxM=,tag:9AjgAow2WGXZ8cWYhQB5XQ==,type:str]
    SECRET_FLAMEBOSS_PASSWORD: ENC[AES256_GCM,data:kSSkwCZriaMaCV+AIWKYjXBl2cC3CxSKe7B8AosMlbE6fg==,iv:COzBnGft7LJ49tNHXowjgV0acqzBtRT5+1iRQbcrgXE=,tag:fVmts/6ZxRxAgBSldGQryg==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:egtGkhTRhy9EsA==,iv:rgrujBAt/PGhTD/MCZSOADh5+3ABi4X8P7IOIYnvYpI=,tag:CsszuzUywZ8yD2DvMhF8yQ==,type:str]
    DID_HALIFAX: ENC[AES256_GCM,data:FMLA+NIEFwq68g==,iv:hLGc/1lTuaJVCJ0ubctI9uwlmOQJZ0SGSkSiXlFWn2M=,tag:3COul62z9FGh0vVwSRSQAw==,type:str]
    DID_OTTAWA: ENC[AES256_GCM,data:3XhTpiAfEuWgPw==,iv:hpxlZBr0qLCJXPZgUN93KKvlJBtIG4FoXq/Y6IfKrng=,tag:f7VpHACmFhyyKjoz48phJw==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTDZVSCszcWVtbkNPbjky
            UU5hdnNaaWZ0OUtFanFlTU9zQkZUTlZkSms4CnorWm9EKzc3MEFFMFhnUzc5dTVo
            Q0ExVUlBR3lsZmpCTnhNNmV5THZuQUkKLS0tIGdQSmppNTNZWmN1Z1hBNVNUd1pl
            aUhjYzExOFByY3hoektubjQ2ZmVaeEEKHJVBXD0bL1bkgcMP5zqR8zAc/DgWRi4c
            mSCRmedgAC51xUH1yQuNtFbSpkh8EvxJZ5xH9V+HoCIcEjzckjdHlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T02:04:17Z"
    mac: ENC[AES256_GCM,data:L4SGHohPcXYRww+7uLiKv7B7I1TG1gttPl+8DK73bIyZy1fbyWoJ+IZuuYcMQq6jHv7WR8xMNu5/ktZREJ8bxSCY4DyEHeptEmf6TU2tLCUiEmJn80OMgrQ3c3om6Fy/ZOcM4xYKGH17IqGDEZyIP5we7vTlvpeHAEM/yEySlWs=,iv:DiuX5RcJNZyV5Fz859OayJthV0Om79t3DhI2IplDO44=,tag:CM/rb3TI0LR636KBluoEfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
