apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:q1z6KIgq9ev7,iv:GgzpyMItcdl1Mbxp/Rc6K4eSdrFzKrG7RQh5JmII6H0=,tag:GAoRqmhDX8UP7DFBxWJEMQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:C6Rbycj+u1tq9w/fMcfqhpywcCU=,iv:vWW50Nut/Tc2ANoFSy90jOk4bOhWdlgmYh2djxxNMl8=,tag:HGCMgqsTbWl9qpImPqib2A==,type:str]
    SECRET_FLAMEBOSS_USERNAME: ENC[AES256_GCM,data:KTm6H9Kuw4I=,iv:y+772cp4CGqWoSYX3FJP+2ZPdKgjnQfxFtMUPI+hnOk=,tag:QYe4lUCahMFDOu43/6YbMA==,type:str]
    SECRET_FLAMEBOSS_PASSWORD: ENC[AES256_GCM,data:z9MjWtAB+XvURzdGh/xS+zGdlUDGTzJ6mA8gEOgHi4PdIg==,iv:OGBYRajnINUe2J1aO16bupkQqdpFEWiaiHnx6Wx2FMU=,tag:z/Yk+e/Tu6Q1qA6zfm+qIA==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:TA9SgYk2q2Zs3A==,iv:5HwW/hT5/WA+7uPZdSWwi3YILBHC+pfETiRfZjD9T4w=,tag:L79K2+C+z6ZhmS4lbneIiQ==,type:str]
    DID_HALIFAX: ENC[AES256_GCM,data:zH+plRBHRtNdug==,iv:FSB9guWIP1fVeUXzFC4htRk+MA+E0oLaknllTRZkVa0=,tag:fM8Tzl8UekwKQu5RJ77ReQ==,type:str]
    DID_OTTAWA: ENC[AES256_GCM,data:AB66QWWk8Cs5Dw==,iv:rRCTU/NSjBy4JNyhCYkvNal3xNsBVDNBkjEaU5ye85k=,tag:uUsExfRYwBjfQGLNHGwplg==,type:str]
    GATEWAY_DOMAIN: ENC[AES256_GCM,data:QoVvwkd9oArMyl/7ZfM7,iv:Xkt4Y2qcR/ehjlNg/rUWu9MDR3N86mWX5dEjIJNrFrg=,tag:PeEMN/lmVSTsAzvUZ97ltA==,type:str]
    GATEWAY_ZONE: ENC[AES256_GCM,data:JhoPydfFVTDdWOc=,iv:a+uByt+E7cKiAodXq03wBzqZLUUVUcHadceEBJRu0FA=,tag:5r1uHYkejObwf1TRhMlhzg==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aHMvc3RyT01BYlNZeWVW
            WWppMUk0R1lKRWVQTkhsekVPNmZyY0xLejIwClR2ZVlTRTNoOGc4TlZLdTN4T2p4
            RVl1b3lwZW5SbGtQOFA5M3AxVHBvUk0KLS0tIHYwQURVUktzR0dYV2dOeVp0VDlY
            aEJPY3BDY3RkcEYxTnJRaFk3OER1aVkKVkFHHXZSOc9fMb5s7I2ISD+FXtPdhUv2
            QMmFan2JzUXzfKqMrIbhL7KJ55sYAp29Sz4MdqAw2O93+/dO4FHL5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T23:32:32Z"
    mac: ENC[AES256_GCM,data:kkJbOIfMAAxixVZz1uWkbK284KyAkbMnm/swnModycuWG5RrQDtGXRJtOQmj76qVxbVxcO674zgqRPgJx2cI3y+UxQda/Smt/EjTnWXZ2ALPADix3akGwJVyglpn2SpIOd2JmL2k+ThpffeBlxWXwInxY5dfhoQToPkPRBe8jpk=,iv:G54ducoL9ld3QLaDobxB/o+vizkB4SubrKTiFVuz48g=,tag:I9zILAWNC56pxYYg1k39+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
