apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hCnFHQUDktkQ,iv:yfn7ID2fh0VuobTHiSKWfxBsVxabZB5OVNn1AZcHq/c=,tag:mPnq0pzZmplG+a75kT1lQA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Swse2Di/sETlhznfrc6sv6lWbUM=,iv:GhoBvLBfZilnDMzplCk+OFuhHPFEEtp2taXHidHqJKY=,tag:eKrXtCmwH7kGe/FU7dVbIw==,type:str]
    SECRET_FLAMEBOSS_USERNAME: ENC[AES256_GCM,data:Oslz5BMgzec=,iv:93wBTfnG/MNKQRBwdlDYmWWnE4JWvUdx1i7FQ6y8mrg=,tag:VsMhUZMN7talj7KuOofXSg==,type:str]
    SECRET_FLAMEBOSS_PASSWORD: ENC[AES256_GCM,data:6AqRokVx+LFthV56QUGb2628JJ6kQSEeHs7EHF0FNHw0SA==,iv:VYmGGVVg+qvz2J6yellOlWOTvHiPpNlNfuyQWjMOfUQ=,tag:0snb+txBQhsaPgh3jxabfQ==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:c9NtcB02281byg==,iv:jok/CizYz32uUeZBMrUyggdO8Ser/KyDxmVVq020uTs=,tag:76o4rgeltlLiJbuxauE7dA==,type:str]
    DID_HALIFAX: ENC[AES256_GCM,data:ezNx/YuFQvAKnA==,iv:gHbw75fLxpXmaasBiBs20AY0dVSBG6D2hh+TguETGlU=,tag:RMvpc8uEeqRdGLwWk1qPfg==,type:str]
    DID_OTTAWA: ENC[AES256_GCM,data:TAeAGmPBUdtFeQ==,iv:gyPqnKwk5W8kVKQYPkmjGzJ/L/09WLYCKwxXcH1k5lw=,tag:2mEN63RqYe9/YEjqQU0sgw==,type:str]
    GATEWAY_DOMAIN: ENC[AES256_GCM,data:7c1MRzXeDPqk5gF26N8j,iv:X0T7mZG7KBKK2AgBgnBit+j+uepa7EvcJLjyAYd2WZE=,tag:8yCvrfRHtbftpKqyWKf/fQ==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaW1TNDhHVndIYkZKSzBM
            V3R5bmFnUUd4Q3RWVG5nVnZrQ2s0Um9yQVFvCmpXTHhaVC9sRndyUnJZVjNxZDdR
            RzNzR2FwWjJqTXcwNzlGd2FpZnVzSzQKLS0tIGxhUXVzaFBvM0haZEpFbXdWUnli
            SDZpQ2NqUk1sU2lHbDFRcjE2M245ancKy6EemYsvCRQn25Vm2w1EIqw2D0ZTAvgE
            dQDQ7uqvw3wm/TrOB0P1NxZOHmorRN71a6EY3SNv1NIjC6NW/a1x8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T22:48:15Z"
    mac: ENC[AES256_GCM,data:6L25Sz5KJxEK2+GON5NK+hJdiBCcCSqaWCjw6hlKO7Xo9B1gh+mGysCCB+Kat9dfpyDzNdVsfEOLtu1p9SKIjbmY+rM0eRSHJMZdSxTtmY1maR3PJ3DeC7fmMa0+jVZznrUt2ia1keR1eidtezxHFlvVs0R7YMbgH7hfv3/v8Ao=,iv:Ok/cGgg9B9IrzaSzh7EuqD56lH8pKDnwoVfErBP7rEU=,tag:9EwPGT0pgn3ipgQl5THdvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
