apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: folly-k8s-lan-router
spec:
  replicas: 1
  hostnamePrefix: folly-k8s-lan-router
  subnetRouter:
    advertiseRoutes:
      - ${CILIUM_NATIVE_ROUTING_CIDR}
      - ${LB_RANGE}
  tags:
    - tag:k8s
    - tag:folly
    - tag:k8s-folly
