apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: folly-k8s-lan-router
spec:
  replicas: 1
  hostnamePrefix: folly-k8s-lan-router
  subnetRouter:
    advertiseRoutes:
      - "10.3.0.0/24"
