apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:F8fFFD300xPzqEn9wjavpB4=,iv:azrErvt7o+TL1bSTrfHlRjSny1WNdFUK9908Rky3F7s=,tag:OSp26q/CvKMEB18dyohpSQ==,type:str]
    client_secret: ENC[AES256_GCM,data:0tP29qaEyXFN64Vi3/H1HgkKHSZizdmPXrL76bYr4gTuD3Eq0RhkjGpUWn+3wPBBk0Y/+qLLl9P0yXrdpgth,iv:rHKmXNiEzTiHy5fM44gi/aOVk8OPDjjbZYocqts5t6o=,tag:iqKp5OOHWBzkJeALJGk+Sw==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMFNJcjg3VE5EVG1wRDdw
            cE82Y1NTRkRJU09MczgwTnIrQnJLQkZwdFhRCjhlM09WSGxSOFdxOEFJanM0ckQ5
            VUhQUTlOdHNxTDZCTytxdTVLa3hLMDAKLS0tIFNNKy84NHZScnRBYnh4RFBpNFR4
            MDRzdWhXVnNYRWFWN1BuUXJkSjB3NEkKyJ8C3DSoRujFbCDP/8cJDzfrhWJ1zI7y
            mqKPs4BllLK36GBpQ/oMt1zEZ0DqRqMBn297XBHQyxIl1YDTU0mKIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T22:21:07Z"
    mac: ENC[AES256_GCM,data:1rP70/PkeM1jwH079zuLSJrO/Xw3G1qyme9hR++lFMOZxbKfa85GScAt/+GUJLM93U8+EoFfooJZhJcz9Tg+EEG/3OXWalDIO9LaHXDjbJjW7TNlFQpktFs2z+GXF5CnTRQW2SEnJJKRfOQSDGigSmUD9MtAIiviFHXDFciFVv8=,iv:rl+BKiaR6jv3nB0q+FLxKl05bs23V6SzIdDiUb85zOI=,tag:tEGQVuZOYE8lPQOHrMBr5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
