---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${GATEWAY_DOMAIN}
spec:
  endpoints:
    - dnsName: ${GATEWAY_DOMAIN}
      recordTTL: 60
      recordType: A
      targets:
        - 10.89.0.1
