---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${GATEWAY_DOMAIN}
  namespace: default
spec:
  endpoints:
    - dnsName: ${GATEWAY_DOMAIN}
      recordTTL: 60
      recordType: A
      targets:
        - 10.1.0.1
        - 10.2.0.1
        - 10.3.0.1
        - 10.13.37.1
