apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: slingshot-gateway
  namespace: slingshot
  annotations:
    cert-manager.io/cluster-issuer: ${CERT_CLUSTER_ISSUER}
spec:
  gatewayClassName: cilium
  listeners:
    - name: http-gateway
      protocol: HTTP
      port: 80
      hostname: &hostname "slingshot.${SECRET_DOMAIN}"
    - name: tls-gateway
      protocol: HTTPS
      port: 443
      hostname: *hostname
      tls:
        certificateRefs:
          - kind: Secret
            name: *hostname
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: slingshot-http-route
  namespace: slingshot
spec:
  parentRefs:
    - name: slingshot-gateway
  hostnames:
    - "slingshot.${SECRET_DOMAIN}"
  rules:
    - backendRefs:
        - name: slingshot
          port: 3000





