apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:e+XacC9Mtp4xtcOgxi1OrE9WCeWbCvRIWaHqy0CJXZomcP3hOcftIQ==,iv:hMXKb8yewp7OPk67xgO118yOEI+X18Kf/SGrH3nGylc=,tag:sK83H4niVSKqKO9ZLT7COA==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL0xtRktzemtVQzZ1bU5Z
            S0RFUG9Za0lJNERMMWc5OXA5UmZaT3RSMEJZCldmNnYyRUYxeE9hcHBVQXQwWDlK
            VStkK0lvZ091UkZ2NUsxUGtoYUcwdkEKLS0tIEFIclptQlpJY2c2MEQvSnJFYmYw
            bEVwN1E3eEJGdDJRR1dvTnlweEpYR2sKRMdn6rC3ZLQw2/ln6l8863htZtJKw93R
            2PI+IOzJ54SuUWv2jdCO1f7ghXnki+Vvg4JyFmdlELNFU3ChnqFoRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T23:58:02Z"
    mac: ENC[AES256_GCM,data:DDeCAw2dgBnZBDSjax1B0iXF1ypkTXSgbZ/IHGzo9QB5S+LF0nF/14O/UZaL30+IbvDrYcGwgVVVvscUhrXXL+pYUishaFBJWE8xVxlH4lPobx1OmL2MXIJpx0WYmSLXLxnbj6NGrODwclKlDYACn9lZJHmF+T17sb76i7guw2A=,iv:U3bmvTQwQUZhqhNPgqdkYW/Ldj5SQXEzza8YIgjX1/s=,tag:IjGMc19S6J5SdNrGQI5BEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
