apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: offsite-k8s-lan-router
spec:
  replicas: 1
  hostnamePrefix: offsite-k8s-lan-router
  subnetRouter:
    advertiseRoutes:
      - ${CILIUM_NATIVE_ROUTING_CIDR}
  tags:
    - tag:k8s
    - tag:k8s-offsite
    - tag:offsite
