apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
stringData:
    client_id: ENC[AES256_GCM,data:2/9LGJ8EnixYjEBBB0AVwzQ=,iv:fon1naqzTnrgrohydvMZYNIRt760St4OoA7IuVyPvUI=,tag:4ktp/8ALw7DmLl0WyHaA7A==,type:str]
    client_secret: ENC[AES256_GCM,data:ne0UYeZ99esKEZmJjC63gF6uvudxmzmOZXqFTIW3hJJmf7MkLOWF4zaQ7cA1BIEypGu7dBIRqlh19N/ms4dx,iv:rndyoUaweCQLATiI3D0e9uWIn033ar1m+2ss1BuJEXM=,tag:JiH4KHuBF5RrymTkSj3WFg==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeXUvV3FuY3NlcUU1bzR2
            TTRhQ0J1L21HT2xQb2RVSmlmMEdLQkl5OGlFClBiU1dveHpXeCtWcHhaNi9XTnBY
            anNJZHY3MVUxeVpEOWQ1dWliVm5veVEKLS0tIEFsTVZzeHNkMi9LRTMra3dUZWVF
            QW16UHNTRGRQbXptZXA2WHB2S3pvVTAKjtZ6Rc9d6lA+khT38xXJi9FVg80iR4+S
            BNJq8or1fZIy844pbGe8Z73orz2vKTwrzJpY7vcbv5BwwbzSurMT0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T22:21:35Z"
    mac: ENC[AES256_GCM,data:M8ZslN7ZBu1uxv5BYjiRr1NmHQ+oExIPcXaZN1xLK4RhkNXVc0ecI3p+ikk9+zs6peYkupVt+ra8vHkKT8745AkI7H/1Izogdabr/IJd3RaltCLWPA76ljuUifLOZyMVaoIxP+TxPZ0vAKOWl8TxV4KyQe2g84LEVgq/0lIUZyc=,iv:N2kANLOiyB/ogWVMvXVAjw7eq7VH7I4s98jIQn7zDB4=,tag:6buZaVlxE89jTIu8A+cmzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
