---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - secret.sops.yaml
namespace: atlantis
configMapGenerator:
  - name: deny-policy
    files:
      - deny-policy.rego
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
