---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - secret.sops.yaml
namespace: atlantis
configMapGenerator:
  - name: policies
    files:
      - policies/default-deny.rego
      - policies/only-me.rego
      - policies/only-me.json
  - name: plan-hook
    files:
      - plan-hook.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
