apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${GATEWAY_DOMAIN}
  namespace: default
spec:
  secretName: ${GATEWAY_DOMAIN}
  dnsNames:
    - ${GATEWAY_DOMAIN}
    - unifi.${GATEWAY_DOMAIN}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
    group: cert-manager.io
