---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arc-infra-folly
  namespace: arc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-reader
  namespace: argo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications", "applicationsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-infra-folly-argocd-reader
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: arc-infra-folly
    namespace: arc
roleRef:
  kind: Role
  name: argocd-reader
  apiGroup: rbac.authorization.k8s.io
