apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_ZONE: ENC[AES256_GCM,data:DibD6xbF0/42,iv:KXm8HeoZ2EcEPkhLpV7qMQAdix90nqHyBe4GflRN3Ic=,tag:wqXKfnS+324baF8LusGRCQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dHXddl0zQ+36,iv:LE26Fn+j4pA5fd9HIM5LGX4gabFJ9mpMaDqrRaQTRWU=,tag:PM999JlhI7NzHoiernT/wQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rvXA5rwaraVW1URS2/zy45PyBxo=,iv:y/Ft9LmYhqm+drQlzJkofd4Y+K/PQehYnI1mX+rYFQ0=,tag:tHtyTL8XcN05/Rob+FJ7qg==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:8S9tZ/Byh80ZeA==,iv:Mf4L0My6BRg9Nb/VKLe9a88fSA9vnMLpbFiXysMKJ8Y=,tag:zNpSYH4acH5oj+dw3u3xKQ==,type:str]
    GATEWAY_DOMAIN: ENC[AES256_GCM,data:M0yHEXBuRyAwA9bTKNZwVQ==,iv:+kKVfGZ1lPRo3aEmK5Zx9GtNCPnEywJtKLHxoTs8SGQ=,tag:75gG+q0BQBMZlLSm0i6PYA==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT08rZFNKcDhPaVpyRXR5
            Nko1NDBmZTNLRldvRDdLK1dUbmwzSnZtOEYwClhvbWY5dEJpMHBrSXZxTXJqaGtE
            ZVdtdFNMTGNla1UzOTRwRFpBOHRDclkKLS0tIHFuQ2ZIYzQ4b3NKQ0drWWY3ZEVT
            VllMTHlyVGhHZVlvbmV2UVBpanlyQzAK4WyD/CdiOWQaLvPPa5ICDzZ4bwn/Kpqw
            wbw8ryrgMheTB2oh1l2ZcNW5pwH+SqLEXTl2dNEYCh87wGeeoLWglA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T22:48:20Z"
    mac: ENC[AES256_GCM,data:VPSE42lSfrK8yLtCdrdaL6CKm1pqDL57Z0MhrpMjnrvjqWHDAkcbJJ3SAqMxdjz5gjYJt2reU4azemOSK0vaoavT6P0mtDymPmQNcG8OYqup0v2VNdA1TwFsz3BXjVeTfgZkzoSHm6RjLUtR8fU2MvBxAGz/P4/L1q6XRaaIN68=,iv:TJRUCDOWFCzolCehyOuehM/slKXFmxs4g7TrDZLXuW0=,tag:lwiY6EZSBn8olpwSKaexPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
