apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Halifax
  API_SERVER_IP: 10.89.0.10
  API_SERVER_PORT: "6443"
  CERT_CLUSTER_ISSUER: letsencrypt-production
  CILIUM_NATIVE_ROUTING_CIDR: 10.89.0.0/24
  CILIUM_POD_CIDR: 10.101.0.0/20
  BGP_ROUTER_IP: 10.89.0.1
  LB_RANGE: 10.89.0.64/26
