apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_ZONE: ENC[AES256_GCM,data:zrGrmZEeqjwl,iv:P5jwkAvZlhd+/7j8HRVVR6mbyAq27l8dnMtAWq33rHk=,tag:M8uvzto0ptHe89+tqRJGuA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:vZ7vPGn9mzza,iv:CefQC5LtZ4ykXUWzopJHt/8aiuw53c9Ff9azsDIwsXs=,tag:FR019kgsqn4psSC7OJqw+g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:fTgfXaWDi722h24d6TR1FdZ0R1k=,iv:HTprodcuo3UWXh9cYdTBvCHS3Qa6Kd1IJAlzIEgU0tQ=,tag:AbX+v/iS3Z2Vw6j6PuDhWw==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:357r7IZmbVZAEA==,iv:OG7FazfAfql4z/fQzihZBtyeSqp61NXlu3bRZxt1t8s=,tag:fPuOfP1jNbMYnqwHDl8f4g==,type:str]
    GATEWAY_DOMAIN: ENC[AES256_GCM,data:FmGCBEUecS5pv/h+goItHA==,iv:S66cb51sJiBhr0TsUR3O7Yz+bEbA0ddrZ+OBHPU816s=,tag:nwcwDjSC76FipBkAngMd5g==,type:str]
    GATEWAY_ZONE: ENC[AES256_GCM,data:Z4/csZ8ErN0YvkI=,iv:KwvDT9RXq67nqlIDQ79YG+wHuMWEHikeJTiFzQO2L3o=,tag:PB9PETk82R919BPYvzeTaQ==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOUxSOVRKNW5pMmFjL2gz
            bXhzMGpJak50ckhvTXQvK3NjN0RKdllxbldVCnBHT1RMTFdLNW1GK2tGL294bUo3
            cWtlNUQ1VlRFa1ZqNUZGNGR1cmdGVWsKLS0tIGhjZTIvSnFEZnhhL05qZjEwWnJW
            K3dIM3J3T3JMQUhIbGdQZ2VBRWtWRE0KIx88V6xM+ByoZI2OLXzO5Ue3gP9LaG/M
            ClIE9T1O9kqTA/rBnWmZ9LQh+s50YcChNWMUoMm1wrisUiH+Qc5G8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T23:32:29Z"
    mac: ENC[AES256_GCM,data:YJ59d/OTnpw9cFD8F0ToK11pPTauzoiYRlLzEzN1KMARpb4PSoWI/Gt94/gJqwReOPhI56Gn1esE5bVqb+oUcw/kaAhvBuiek2xMLYjYBSRWg2bwOEhSt0JvJPC/4fVPkWCsyC9czzPJJhRcKMOLsX69MUH6kVX1X5sL4H+TLRI=,iv:IEu3JEi8MeyfIrBiQn68eoTkRb18fFSxmzau6ixtwXY=,tag:2M9R85Yhk9H2WPLehNhtrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
