apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_ZONE: ENC[AES256_GCM,data:MZWpwIJCvQQn,iv:sDz5qWyL5XVvjVLkrA3twfEvgxatsOgP541mu9FtdE8=,tag:nRS0CMJc3ii/z/MC/F+DHw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:HuW276OTPrAK,iv:4cQQehYB/o+8mbJ3SRCrNtXsMmepkojqr7aN4ukNhIw=,tag:LsdMF+PvSH1cn2RxfqCQmA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2WM8sy9dYlDQtBQjJ7ZXDm0HAdY=,iv:OtmGqfgitcOPM5Roh9DjNWNLHDTPzFNCH5rlpOOb5Us=,tag:3W2EbC0meUUH1IJxMCRC+w==,type:str]
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:N56fV9SLI5xRtg==,iv:oxNj3s25xZfSVmoBVTOke+o9eY0xLKBcF+6nM4ACLxE=,tag:YzxrqQzdcRDSw1XV8FhiUQ==,type:str]
sops:
    age:
        - recipient: age1lpfxcn6qwrgtxzymzcxqu20cppsrhmgcpma59sc8ahq9t0w67d3sj8e3e6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmekRmUWlEQ1Vuc1lxZUJF
            OWhOTUNicFJGQTF5S3F3UGJhdmlCejNmNnpNCmdlZFdGOVlnMlhLbnJMKytHS2hY
            Q1RnZEdpWDRWVHg0YzNrWkY2SnFPaGcKLS0tIEhOeGJpUU4wN1UvUnZSWEYrSmpI
            Zm1BYVBXNDN6WERIOC9LeC9Pcm5BSzQKxjFEZRN0X3aagDGeLE8lxlhCUAxjJ+qM
            4qX0VTO4LvPbKvOv1fgAmJyvWw/YClI55e6rQg4Zpp0JzF7+dN0yDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T02:04:35Z"
    mac: ENC[AES256_GCM,data:+ww+HgkoA40dEkFZsBhi4a6M3OmkLBrB8bn/1/BdR+MOXeAgi5La8auajZnQNEDoz+5R08q3DhFToI2UeRVefRTKwCbfxnbX1Ui9xWx6oS5WQ3WfUglET2zZwRYCpUVxBSrHYuROq1VjfOwiAE2CoJM+F0ORMkYiX5haLy6we6I=,iv:7tLSp/coP9rJSkqu3EOO797btoKdGC1bLKsZP2LLs9E=,tag:VJ5Q2+LLLSQk7tLPABW6gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
