---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/clusters/folly/networking/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-endpoints
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./k8s/clusters/folly/networking/external-dns/endpoints
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  dependsOn:
    - name: external-dns
