---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - gateway-api.yaml
  - cilium
  - cloudflare
  - external-dns.yaml
  - tailscale
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    patch: |-
      - op: replace
        path: /spec/interval
        value: 1m0s
      - op: replace
        path: /spec/chart/spec/interval
        value: 5m0s
      - op: replace
        path: /spec/maxHistory
        value: 2
